[build-system]
requires = ["scikit-build-core >=0.4.3", "nanobind >=1.3.2"]
build-backend = "scikit_build_core.build"

[project]
name = "bochscpu-python"
version = "0.1.3"
description = "Python bindings for BochsCPU."
readme = "./README.md"
license.file = "./LICENSE"
requires-python = ">=3.8"
authors = [{ name = "hugsy", email = "hugsy@blah.cat" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: System :: Emulators",
    "Natural Language :: English",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/hugsy/bochscpu-python"

[tool.isort]
profile = "black"

[tool.scikit-build]
wheel.py-api = "cp312"
minimum-version = "0.4"
build-dir = "build/{wheel_tag}"
cmake.minimum-version = "3.20"
