import bochscpu.cpu

class ControlRegister:
    @property
    def AM(self) -> bool: ...
    @AM.setter
    def AM(self) -> bool: ...
    @property
    def CD(self) -> bool: ...
    @CD.setter
    def CD(self) -> bool: ...
    @property
    def DE(self) -> bool: ...
    @DE.setter
    def DE(self) -> bool: ...
    @property
    def EM(self) -> bool: ...
    @EM.setter
    def EM(self) -> bool: ...
    @property
    def ET(self) -> bool: ...
    @ET.setter
    def ET(self) -> bool: ...
    @property
    def FSGSBASE(self) -> bool: ...
    @FSGSBASE.setter
    def FSGSBASE(self) -> bool: ...
    @property
    def MCE(self) -> bool: ...
    @MCE.setter
    def MCE(self) -> bool: ...
    @property
    def MP(self) -> bool: ...
    @MP.setter
    def MP(self) -> bool: ...
    @property
    def NE(self) -> bool: ...
    @NE.setter
    def NE(self) -> bool: ...
    @property
    def NW(self) -> bool: ...
    @NW.setter
    def NW(self) -> bool: ...
    @property
    def OSFXSR(self) -> bool: ...
    @OSFXSR.setter
    def OSFXSR(self) -> bool: ...
    @property
    def OSXMMEXCPT(self) -> bool: ...
    @OSXMMEXCPT.setter
    def OSXMMEXCPT(self) -> bool: ...
    @property
    def OSXSAVE(self) -> bool: ...
    @OSXSAVE.setter
    def OSXSAVE(self) -> bool: ...
    @property
    def PAE(self) -> bool: ...
    @PAE.setter
    def PAE(self) -> bool: ...
    @property
    def PCE(self) -> bool: ...
    @PCE.setter
    def PCE(self) -> bool: ...
    @property
    def PE(self) -> bool: ...
    @PE.setter
    def PE(self) -> bool: ...
    @property
    def PG(self) -> bool: ...
    @PG.setter
    def PG(self) -> bool: ...
    @property
    def PGE(self) -> bool: ...
    @PGE.setter
    def PGE(self) -> bool: ...
    @property
    def PSE(self) -> bool: ...
    @PSE.setter
    def PSE(self) -> bool: ...
    @property
    def PVI(self) -> bool: ...
    @PVI.setter
    def PVI(self) -> bool: ...
    @property
    def TS(self) -> bool: ...
    @TS.setter
    def TS(self) -> bool: ...
    @property
    def TSD(self) -> bool: ...
    @TSD.setter
    def TSD(self) -> bool: ...
    @property
    def VME(self) -> bool: ...
    @VME.setter
    def VME(self) -> bool: ...
    @property
    def WP(self) -> bool: ...
    @WP.setter
    def WP(self) -> bool: ...
    def __init__(self) -> None: ...

class ControlRegisterFlag:
    """
    <attribute '__doc__' of 'ControlRegisterFlag' objects>
    """

    AM: ControlRegisterFlag
    CD: ControlRegisterFlag
    DE: ControlRegisterFlag
    EM: ControlRegisterFlag
    ET: ControlRegisterFlag
    FSGSBASE: ControlRegisterFlag
    MCE: ControlRegisterFlag
    MP: ControlRegisterFlag
    NE: ControlRegisterFlag
    NW: ControlRegisterFlag
    OSFXSR: ControlRegisterFlag
    OSXMMEXCPT: ControlRegisterFlag
    OSXSAVE: ControlRegisterFlag
    PAE: ControlRegisterFlag
    PCE: ControlRegisterFlag
    PE: ControlRegisterFlag
    PG: ControlRegisterFlag
    PGE: ControlRegisterFlag
    PSE: ControlRegisterFlag
    PVI: ControlRegisterFlag
    TS: ControlRegisterFlag
    TSD: ControlRegisterFlag
    VME: ControlRegisterFlag
    WP: ControlRegisterFlag

    def __init__(*args, **kwargs):
        """
        Initialize self.  See help(type(self)) for accurate signature.
        """
        ...

DE: ControlRegisterFlag

FSGSBASE: ControlRegisterFlag

MCE: ControlRegisterFlag

NW: ControlRegisterFlag

OSFXSR: ControlRegisterFlag

OSXMMEXCPT: ControlRegisterFlag

OSXSAVE: ControlRegisterFlag

PAE: ControlRegisterFlag

PCE: ControlRegisterFlag

PG: ControlRegisterFlag

PGE: ControlRegisterFlag

PSE: ControlRegisterFlag

PVI: ControlRegisterFlag

TSD: ControlRegisterFlag

VME: ControlRegisterFlag

class cpu:
    def __init__(*args, **kwargs):
        """
        Initialize self.  See help(type(self)) for accurate signature.
        """
        ...
    @property
    def cr2(self) -> int: ...
    @cr2.setter
    def cr2(self) -> int: ...
    @property
    def cr3(self) -> int: ...
    @cr3.setter
    def cr3(self) -> int: ...
    @property
    def cs(self) -> bochscpu.Segment: ...
    @cs.setter
    def cs(self) -> bochscpu.Segment: ...
    @property
    def ds(self) -> bochscpu.Segment: ...
    @ds.setter
    def ds(self) -> bochscpu.Segment: ...
    @property
    def es(self) -> bochscpu.Segment: ...
    @es.setter
    def es(self) -> bochscpu.Segment: ...
    @property
    def fs(self) -> bochscpu.Segment: ...
    @fs.setter
    def fs(self) -> bochscpu.Segment: ...
    @property
    def gdtr(self) -> bochscpu.GlobalSegment: ...
    @gdtr.setter
    def gdtr(self) -> bochscpu.GlobalSegment: ...
    @property
    def gs(self) -> bochscpu.Segment: ...
    @gs.setter
    def gs(self) -> bochscpu.Segment: ...
    @property
    def id(self) -> int: ...
    @property
    def idtr(self) -> bochscpu.GlobalSegment: ...
    @idtr.setter
    def idtr(self) -> bochscpu.GlobalSegment: ...
    @property
    def ldtr(self) -> bochscpu.Segment: ...
    @ldtr.setter
    def ldtr(self) -> bochscpu.Segment: ...
    @property
    def r10(self) -> int: ...
    @r10.setter
    def r10(self) -> int: ...
    @property
    def r11(self) -> int: ...
    @r11.setter
    def r11(self) -> int: ...
    @property
    def r12(self) -> int: ...
    @r12.setter
    def r12(self) -> int: ...
    @property
    def r13(self) -> int: ...
    @r13.setter
    def r13(self) -> int: ...
    @property
    def r14(self) -> int: ...
    @r14.setter
    def r14(self) -> int: ...
    @property
    def r15(self) -> int: ...
    @r15.setter
    def r15(self) -> int: ...
    @property
    def r8(self) -> int: ...
    @r8.setter
    def r8(self) -> int: ...
    @property
    def r9(self) -> int: ...
    @r9.setter
    def r9(self) -> int: ...
    @property
    def rax(self) -> int: ...
    @rax.setter
    def rax(self) -> int: ...
    @property
    def rbp(self) -> int: ...
    @rbp.setter
    def rbp(self) -> int: ...
    @property
    def rbx(self) -> int: ...
    @rbx.setter
    def rbx(self) -> int: ...
    @property
    def rcx(self) -> int: ...
    @rcx.setter
    def rcx(self) -> int: ...
    @property
    def rdi(self) -> int: ...
    @rdi.setter
    def rdi(self) -> int: ...
    @property
    def rdx(self) -> int: ...
    @rdx.setter
    def rdx(self) -> int: ...
    @property
    def rflags(self) -> int: ...
    @rflags.setter
    def rflags(self) -> int: ...
    @property
    def rip(self) -> int: ...
    @rip.setter
    def rip(self) -> int: ...
    @property
    def rsi(self) -> int: ...
    @rsi.setter
    def rsi(self) -> int: ...
    @property
    def rsp(self) -> int: ...
    @rsp.setter
    def rsp(self) -> int: ...
    def set_exception(self, vector: int, error: int) -> None: ...
    def set_mode(self) -> None: ...
    def set_state_no_flush(self, state: bochscpu.State) -> None: ...
    @property
    def ss(self) -> bochscpu.Segment: ...
    @ss.setter
    def ss(self) -> bochscpu.Segment: ...
    @property
    def state(self) -> bochscpu.State: ...
    @state.setter
    def state(self) -> bochscpu.State: ...
    @property
    def tr(self) -> bochscpu.Segment: ...
    @tr.setter
    def tr(self) -> bochscpu.Segment: ...
    @property
    def zmm(self) -> bochscpu.Zmm: ...
    @zmm.setter
    def zmm(self, arg: int, /) -> bochscpu.Zmm: ...
